#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the angryProfessor function below.
def angryProfessor(k, a):
    ontime=0
    late=0
    for _ in a:
        if _<=0:
            ontime+=1
        else:
            late+=1
    if ontime>=k:
        print('NO')
    else:
        print('YES')

if __name__ == '__main__':
    t = int(input())

    for t_itr in range(t):
        nk = input().split()

        n = int(nk[0])

        k = int(nk[1])

        a = list(map(int, input().rstrip().split()))

        result = angryProfessor(k, a)
