#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the solve function below.
def solve(s):

    s_ar = s.split(' ')

    final_ar = []

    for w in s_ar:

        final_ar.append(w.capitalize())

    out=' '.join(final_ar)
    return out

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = solve(s)

    fptr.write(result + '\n')

    fptr.close()
