#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the compareTriplets function below.
def compareTriplets(a, b):
    alicep=0
    bobp=0

    for i in range(3):
        if a[i]>b[i]:
            alicep+=1
        elif b[i]>a[i]:
            bobp+=1
    
    print(f'{alicep} {bobp}')

if __name__ == '__main__':

    a = list(map(int, input().rstrip().split()))

    b = list(map(int, input().rstrip().split()))

    result = compareTriplets(a, b)

