#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the designerPdfViewer function below.
def designerPdfViewer(h, word):
    width=len(word)
    charlist=['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
    mydict={}
    for x in range(len(charlist)):
        mydict[charlist[x]]=h[x]
    
    hlist=list()

    for item in word:
        hlist.append(mydict[item])
    
    print(width*max(hlist))


if __name__ == '__main__':
    h = list(map(int, input().rstrip().split()))

    word = input()

    result = designerPdfViewer(h, word)

