#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'diagonalDifference' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY arr as parameter.
#

def diagonalDifference(arr):
    primarysum=0

    secondarysum=0

    for i in range(n):
        primarysum+=arr[i][i]
    for j in range(n-1,-1,-1):
        secondarysum+=arr[j][n-j-1]
    
    if secondarysum>primarysum:
        return secondarysum-primarysum
    else:
        return primarysum-secondarysum

    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    result = diagonalDifference(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
