#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the findDigits function below.
def findDigits(n):
    mystr=str(n)
    divisorlist=[]
    for _ in mystr:
        divisorlist.append(int(_))
    count=0
    for _ in divisorlist:
        if not _==0:
            if n%_==0:
                count+=1
    return count

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    for t_itr in range(t):
        n = int(input())

        result = findDigits(n)

        fptr.write(str(result) + '\n')

    fptr.close()
