#!/bin/python3

import math
import os

# Complete the squares function below.

def squares(a, b):
    i=math.ceil(a**0.5)
    j=math.floor(b**0.5)
    return j-i+1


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input())

    for q_itr in range(q):
        ab = input().split()

        a = int(ab[0])

        b = int(ab[1])

        result = squares(a, b)

        fptr.write(str(result) + '\n')

    fptr.close()
