#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the utopianTree function below.
def utopianTree(n):
    height=1

    for i in range(1,n+1):
        if not i%2==0:
            height*=2
        else:
            height+=1

    print(height)

if __name__ == '__main__':

    t = int(input())

    for t_itr in range(t):
        n = int(input())

        result = utopianTree(n)
