#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the viralAdvertising function below.
def viralAdvertising(n):
    recipient=5
    liked=0
    count=0
    for i in range(1,n+1):
        liked=int(recipient/2)
        count+=liked
        recipient=liked*3
    print(count)
    
if __name__ == '__main__':

    n = int(input())

    result = viralAdvertising(n)
